'use strict';
const text = {
 en:{url:'Server API URL',key:'Admin API key',demo:'Demo data',connect:'Connect',disconnect:'Disconnect',interval:'Poll interval (seconds)',apply:'Apply',open:'Open MyScoutee ↗',profiles:'Profiles',active:'Active profiles',week:'Registrations · 7 days',month:'Registrations · 30 days',attention:'Needs attention',background:'You can close this window. The monitor keeps running until you disconnect or stop it. Open MyScoutee and sign in to handle cases.',connected:'Connected',connecting:'Connecting…',disconnected:'Disconnected',snapshot:'Statistics snapshot',female:'Women',male:'Men',unreadMessages:'Unread messages',unresolvedReports:'Unresolved reports',unresolvedFeedback:'Unresolved feedback',supportCases:'Open support cases',failedJobs:'Failed Jobs',newActivity:'New admin activity — open MyScoutee to review.',waiting:'Waiting for the statistics snapshot.',authorization_failed:'Key expired/revoked or admin access removed. Reconnect with a valid key.',connection_failed:'Connection failed. Keeping the last data; polling will retry.',invalid_url:'Enter the complete API URL.',https_required:'Remote servers require HTTPS. HTTP is allowed only on localhost.',invalid_key:'Enter an API key.',invalid_interval:'Choose 5–3600 seconds.',invalid_request:'Invalid request.',local_failed:'The local monitor is unavailable. Reopen the application.',no_control:'Open this window using the application launcher.'},
 hu:{url:'Szerver API URL',key:'Admin API-kulcs',demo:'Demóadatok',connect:'Kapcsolódás',disconnect:'Leválasztás',interval:'Lekérdezés (másodperc)',apply:'Alkalmaz',open:'MyScoutee megnyitása ↗',profiles:'Profilok',active:'Aktív profilok',week:'Regisztrációk · 7 nap',month:'Regisztrációk · 30 nap',attention:'Figyelmet igényel',background:'Az ablak bezárható. A figyelő a leválasztásig vagy leállításig fut. Az ügyek intézéséhez nyisd meg a MyScoutee-t és jelentkezz be.',connected:'Kapcsolódva',connecting:'Kapcsolódás…',disconnected:'Leválasztva',snapshot:'Statisztika időpontja',female:'Nők',male:'Férfiak',unreadMessages:'Olvasatlan üzenetek',unresolvedReports:'Megoldatlan jelentések',unresolvedFeedback:'Megoldatlan visszajelzések',supportCases:'Nyitott támogatási ügyek',failedJobs:'Sikertelen Jobok',newActivity:'Új adminisztrátori teendő — nyisd meg a MyScoutee-t.',waiting:'Várakozás a statisztikára.',authorization_failed:'A kulcs lejárt/visszavonták, vagy megszűnt az adminjog. Kapcsolódj érvényes kulccsal.',connection_failed:'Kapcsolódási hiba. Az utolsó adatok látszanak; a figyelő újrapróbálja.',invalid_url:'Add meg a teljes API URL-t.',https_required:'Távoli szerverhez HTTPS szükséges. HTTP csak localhoston használható.',invalid_key:'Adj meg egy API-kulcsot.',invalid_interval:'Válassz 5–3600 másodpercet.',invalid_request:'Érvénytelen kérés.',local_failed:'A helyi figyelő nem elérhető. Nyisd meg újra az alkalmazást.',no_control:'Az alkalmazás indítójával nyisd meg ezt az ablakot.'}
};
const $ = id => document.getElementById(id);
const control = new URLSearchParams(location.hash.slice(1)).get('control') || sessionStorage.getItem('monitor-control') || '';
if(control) sessionStorage.setItem('monitor-control',control);
history.replaceState(null,'',location.pathname);
let language='en', initialized=false, current=null, busy=false;
function translate(){document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=text[language][el.dataset.i18n]);if(current)render(current);}
async function api(path,body){const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'X-Monitor-Control':control,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'local_failed');return data;}
function render(state){current=state;const t=text[language];if(!initialized){for(const name of ['url','interval'])$(name).value=state.preferences[name];$('demo').checked=state.preferences.demo;language=state.preferences.language||'en';$('language').value=language;initialized=true;translate();return;}
 for(const name of ['url','key','demo','connect'])$(name).disabled=busy||state.connected;$('disconnect').disabled=busy||!state.connected;
 $('key').placeholder=state.connected?(state.keyPreview||''):'';
 $('status').textContent=t[state.connected?(state.lastSuccess?'connected':'connecting'):'disconnected'];$('error').textContent=t[state.error]||'';
 const stats=state.data?.statistics;for(const [id,key]of [['active','activeProfiles'],['week','registrations7Days'],['month','registrations30Days']])$(id).textContent=stats?.ready?stats[key]:'—';
 $('genders').textContent=stats?.ready?['female','male'].map(key=>`${t[key]}: ${stats.genders[key]||0}`).join(' · '):t.waiting;
 $('snapshot').textContent=stats?.generatedAtIso?`${t.snapshot}: ${new Date(stats.generatedAtIso).toLocaleString(language)}`:'';
 $('attention').replaceChildren();for(const key of ['unreadMessages','unresolvedReports','unresolvedFeedback','supportCases','failedJobs']){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t[key];dd.textContent=state.data?.attention?.[key]??'—';$('attention').append(dt,dd);}
 $('notification').textContent=state.connected&&state.alertSequence?t.newActivity:'';
 try{const url=new URL(state.preferences.url);$('open-app').href=url.origin+'/admin';}catch{$('open-app').removeAttribute('href');}}
async function action(path,body){busy=true;try{await api(path,body);$('key').value='';render(await api('/state'));}catch(error){$('error').textContent=text[language][error.message]||text[language].local_failed;}finally{busy=false;if(current){$('connect').disabled=current.connected;$('disconnect').disabled=!current.connected;}}}
$('connection').onsubmit=event=>{event.preventDefault();action('/connect',{url:$('url').value,key:$('key').value,interval:Number($('interval').value),demo:$('demo').checked,language});};
$('disconnect').onclick=()=>action('/disconnect',{});
$('apply').onclick=()=>action('/interval',{interval:Number($('interval').value),language});
$('language').onchange=()=>{language=$('language').value;translate();};
async function poll(){try{if(!control)throw new Error('no_control');render(await api('/state'));}catch(error){$('error').textContent=text[language][error.message]||text[language].local_failed;}setTimeout(poll,1000);}
translate();poll();
